### ISSUE TITLE
Native module not working on Linux

### ISSUE THREAD

**Issue by tritao** [saghul/txiki.js#159] opened 2020-12-13 03:24 UTC
I've got a very simple example with a JS file importing a native module (shared object).

It works fine under `qjs` but fails under `tjs` interpreter.

The .so file is exporting a couple of functions, and I can call them fine with `qjs`, so this seems to be strictly an issue with `tjs`.

JS file:

```javascript
import * as test from "./libtest.so";
```

Output:

```
SyntaxError: unexpected token in expression: ''
    at libtest.so:1
```

Any idea where it's going wrong?

**Comment by saghul** [comment] 2020-12-14 20:54
Can you share the source so I can try to reproduce it?

**Comment by tritao** [comment] 2020-12-14 23:44
Uploaded an archive which contains both the sources and a precompiled binary if you need it.

[quickjs.tar.gz](https://github.com/saghul/txiki.js/files/5692228/quickjs.tar.gz)

Repro:

```
# make -C gen
# tjs test.js
SyntaxError: unexpected token in expression: ''
```

Repo source: https://github.com/mono/CppSharp/tree/master/tests2

**Comment by kaosat-dev** [comment] 2020-12-22 13:36
hi ! 
I can also reproduce this error, with the same error message.
If you need, I have a few minimal .so files around for testing/debuging.
Thanks for the fantastic work on Txiki btw :)

**Comment by saghul** [comment] 2020-12-22 13:54
Ah wait, I hadn't noticed this was a dynamic library. txiki.js doesn't currently support that. See the module loader: https://github.com/saghul/txiki.js/blob/27457e6c651f93a51720e727c1f7fb17771fc540/src/modules.c#L71

I don't remember why I removed support for it, but adding it back should be simple enough.

**Comment by saghul** [comment] 2022-02-04 13:35
I'm going to close this as `wontfix` for now. I'd like to give FFI a go before supporting native modules, which can get complex because they may want to access also the underlying libraries we use.

**Closed by saghul** 2022-02-04 13:35 UTC
